org: jemboaba

app: gen-s3-signed-url

service: presigned-url-generator

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.generator
    environment:
      BUCKET_NAME: NOME_DO_BUCKET