# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jemboaba
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: gen-s3-signed-url
# "service" is the name of this project. This will also be added to your AWS resource names.
service: presigned-url-generator

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.generator
    environment:
      BUCKET_NAME: t-techevents-images
